### ISSUE TITLE
pygame library error

### ISSUE THREAD

**Issue by fayyash99** [iArauf/CP19_45#1]
carImg = pygame.image.load('racecar.png')
pygame.error: Couldn't open racecar.png

**Comment by syedjafri1534** [comment]
import socket
T_PORT = 60
TCP_IP = '127.0.0.1'
BUF_SIZE = 30
# create a socket object name 'k'
k = socket.socket (socket.AF_INET, socket.SOCK_STREAM)
k.bind((TCP_IP, T_PORT))
k.listen(1)
con, addr = k.accept()
print ('Connection Address is: ' , addr)
while True :
    data = con.recv(BUF_SIZE)
if not data:
    break
print ("Received data", data)
con.send(data)
con.close()
